Revert "Merge branch 'docker-mailserver:master' into master"
This reverts commit 1042ed0fed95cdf85dfb57aaf41032458f69d598, reversing
changes made to 6ac2050ed6792d33b1eb883ecef498ea2e2035d1.

diff --git a/target/bin/delmailuser b/target/bin/delmailuser
--- a/target/bin/delmailuser
+++ b/target/bin/delmailuser
@@ -8,10 +8,10 @@
 # shellcheck source=../scripts/helpers/index.sh
 source /usr/local/bin/helpers/index.sh
 
-DATABASE='/tmp/docker-mailserver/postfix-accounts.cf'
-ALIAS_DATABASE='/tmp/docker-mailserver/postfix-virtual.cf'
-QUOTA_DATABASE='/tmp/docker-mailserver/dovecot-quotas.cf'
-MAILDEL='false'
+DATABASE=${DATABASE:-/tmp/docker-mailserver/postfix-accounts.cf}
+ALIAS_DATABASE="/tmp/docker-mailserver/postfix-virtual.cf"
+QUOTA_DATABASE="/tmp/docker-mailserver/dovecot-quotas.cf"
+MAILDEL=false
 
 function __usage
 {
@@ -55,31 +55,31 @@ fi
 
 while getopts ":yYh" OPT
 do
-  case "${OPT}" in
-    ( 'y' | 'Y' )
+  case ${OPT} in
+    y | Y )
       MAILDEL=true
       ;;
 
-    ( 'h' )
+    h )
       __usage
       exit 0
       ;;
 
-    ( * )
+    * )
       __usage
-      _exit_with_error "The option '${OPT}' is unknown"
+      _errex "The option ${OPT} is unknown."
       ;;
 
   esac
 done
 shift $((OPTIND-1))
 
-[[ -z ${*} ]] && { __usage ; _exit_with_error 'No user specified' ; }
+[[ -z ${*} ]] && { __usage ; _errex "No user specifed" ; }
 [[ -s ${DATABASE} ]] || exit 0
 
 if ! ${MAILDEL}
 then
-  read -r -p "Do you want to delete the mailbox as well (removing all mails)? [Y/n] " MAILDEL_CHOSEN
+  read -r -p "Do you want to delete the mailbox as well (removing all mails) ? [Y/n] " MAILDEL_CHOSEN
   if [[ ${MAILDEL_CHOSEN} =~ (y|Y|yes|Yes) ]] || [[ -z ${MAILDEL_CHOSEN} ]]
   then
     MAILDEL=true
@@ -103,7 +103,7 @@ do
   then
     if ! sedfile --strict -i "/^${EMAIL}|/d" "${DATABASE}"
     then
-      _log 'error' "'${UNESCAPED_EMAIL}' couldn't be deleted in '${DATABASE}'"
+      echo "${UNESCAPED_EMAIL} couldn't be deleted in ${DATABASE}." >&2
       ERROR=true
     fi
   fi
@@ -116,9 +116,9 @@ do
       -e "/ ${EMAIL}$/d" -e "s/,${EMAIL}//g" -e "s/${EMAIL},//g" \
       "${ALIAS_DATABASE}"
     then
-      _log 'info' "'${UNESCAPED_EMAIL}' and potential aliases deleted"
+      echo "${UNESCAPED_EMAIL} and potential aliases deleted."
     else
-      _log 'error' "Aliases for '${UNESCAPED_EMAIL}' couldn't be deleted in '${ALIAS_DATABASE}'"
+      echo "Aliases for ${UNESCAPED_EMAIL} couldn't be deleted in ${ALIAS_DATABASE}." >&2
       ERROR=true
     fi
   fi
@@ -128,7 +128,7 @@ do
   then
     if ! sedfile --strict -i -e "/^${EMAIL}:.*$/d" "${QUOTA_DATABASE}"
     then
-      _log 'warn' "Quota for '${UNESCAPED_EMAIL}' couldn't be deleted in '${QUOTA_DATABASE}'"
+      echo "Quota for ${UNESCAPED_EMAIL} couldn't be deleted in ${QUOTA_DATABASE}." >&2
     fi
   fi
 
@@ -144,18 +144,17 @@ use 'sudo docker exec mailserver rm -R /var/mail/${DOMAIN}/${USER}'"
   then
     if rm -R "/var/mail/${DOMAIN}/${USER}"
     then
-      _log 'info' 'Mailbox deleted'
+      echo "Mailbox deleted."
     else
-      _log 'error' 'Mailbox could not be deleted'
+      echo "Mailbox couldn't be deleted." >&2
       ERROR=true
     fi
-    rmdir "/var/mail/${DOMAIN}" &>/dev/null
+    rmdir "/var/mail/${DOMAIN}" 2>/dev/null || true
   else
-    log 'error' "Mailbox directory '/var/mail/${DOMAIN}/${USER}' did not exist"
+    echo "Mailbox directory '/var/mail/${DOMAIN}/${USER}' did not exist." >&2
     ERROR=true
   fi
 
-  ${ERROR} && _exit_with_error 'See the messages above.'
+  ${ERROR} && _errex 'See the messages above.'
 done
-
 exit 0
diff --git a/target/bin/fail2ban b/target/bin/fail2ban
--- a/target/bin/fail2ban
+++ b/target/bin/fail2ban
@@ -3,12 +3,28 @@
 # shellcheck source=../scripts/helpers/index.sh
 source /usr/local/bin/helpers/index.sh
 
-function __usage { echo "Usage: ./setup.sh fail2ban [<ban|unban> <IP>]" ; }
+if ! IPTABLES_OUTPUT=$(iptables -L -n 2>&1)
+then
+  echo "IPTables is not functioning correctly. The output of \`iptables -L\` was:
+
+${IPTABLES_OUTPUT}
+
+Possible causes for this error are
+
+1. Missing capabilities (you need CAP_NET_RAW & CAP_NET_ADMIN, see \`capsh --print\`)
+2. Modifications caused by user-patches.sh
+3. Host is configured incorrectly
+
+Aborting...
+"
+
+  exit 1
+fi
+
+function usage { echo "Usage: ${0} [<unban> <ip-address>]" ; }
 
 unset JAILS
 declare -a JAILS
-IP_REGEXP='((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'
-
 for LIST in $(fail2ban-client status | grep "Jail list" | cut -f2- | sed 's/,/ /g')
 do
   JAILS+=("${LIST}")
@@ -16,67 +32,50 @@ done
 
 if [[ -z ${1} ]]
 then
-  IPS_BANNED=0
+
+  IP_COUNT=0
 
   for JAIL in "${JAILS[@]}"
   do
-    BANNED_IPS=$(fail2ban-client status "${JAIL}" \
-      | grep 'Banned IP list' \
-      | grep -oE "${IP_REGEXP}")
+    BANNED_IP="$(iptables -L "f2b-${JAIL}" -n 2>/dev/null | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -v '0.0.0.0')"
 
-    if [[ -n ${BANNED_IPS} ]]
+    if [[ -n ${BANNED_IP} ]]
     then
-      echo "Banned in ${JAIL}: ${BANNED_IPS//$'\n'/, }"
-      IPS_BANNED=1
+      echo "Banned in ${JAIL}: ${BANNED_IP//$'\n'/, }"
+      IP_COUNT=$(( IP_COUNT + 1 ))
     fi
   done
 
-  [[ ${IPS_BANNED} -eq 0 ]] && _log 'info' "No IPs have been banned"
+  if [[ ${IP_COUNT} -eq 0 ]]
+  then
+    echo "No IPs have been banned."
+  fi
+
 else
 
-  case "${1}" in
+  case ${1} in
 
-    ( 'help' ) __usage ; exit ;;
-
-    ( 'ban' )
-      shift
-      if [[ -n ${1} ]]
-      then
-        RESULT=$(fail2ban-client set custom banip "${@}")
-        if [[ ${RESULT} -gt 0 ]]
-        then
-          echo "Banned custom IP: ${RESULT}"
-        else
-          _log 'error' "Banning '${*}' failed. Already banned?"
-        fi
-
-      else
-        _log 'warn' "You need to specify an IP address: Run './setup.sh fail2ban ban <IP>'"
-        exit 0
-      fi
-      ;;
-
-    ( 'unban' )
+    unban)
       shift
       if [[ -n ${1} ]]
       then
 
         for JAIL in "${JAILS[@]}"
         do
-          RESULT=$(fail2ban-client set "${JAIL}" unbanip "${@}" 2>&1)
+          RESULT="$(fail2ban-client set "${JAIL}" unbanip "${@}" 2>&1)"
 
-          [[ ${RESULT} != *"is not banned"* ]] && [[ ${RESULT} != *"NOK"* ]] && echo "Unbanned IP from ${JAIL}: ${RESULT}"
+          [[ ${RESULT} != *"is not banned"* ]] && [[ ${RESULT} != *"NOK"* ]] && echo -e "Unbanned IP from ${JAIL}: ${RESULT}"
         done
 
       else
-        _log 'warn' "You need to specify an IP address: Run './setup.sh fail2ban' to get a list of banned IP addresses"
+        echo "You need to specify an IP address. Run './setup.sh debug fail2ban' to get a list of banned IP addresses." >&2
         exit 0
       fi
       ;;
 
-    ( * )
-      __usage
-      _exit_with_error "Unknown command '${1}'"
+    *)
+      usage
+      _errex "unknown command: ${1}"
       ;;
 
   esac
diff --git a/target/bin/open-dkim b/target/bin/open-dkim
--- a/target/bin/open-dkim
+++ b/target/bin/open-dkim
@@ -1,8 +1,5 @@
 #! /bin/bash
 
-# shellcheck source=../scripts/helpers/index.sh
-source /usr/local/bin/helpers/index.sh
-
 KEYSIZE=4096
 SELECTOR=mail
 DOMAINS=
@@ -55,44 +52,48 @@ function __usage
 
 while [[ ${#} -gt 0 ]]
 do
-  case "${1}" in
-    ( 'keysize' )
-      if [[ -n ${2+set} ]]
+  case ${1} in
+    keysize )
+      if [[ -n ${2+'set'} ]]
       then
         KEYSIZE="${2}"
         shift
         shift
       else
-        _exit_with_error "No keysize provided after 'keysize' argument"
+        echo "No keysize provided after 'keysize' argument. Aborting." >&2
+        exit 2
       fi
       ;;
 
-    ( 'selector' )
-      if [[ -n ${2+set} ]]
+    selector )
+      if [[ -n ${2+'set'} ]]
       then
         # shellcheck disable=SC2034
         SELECTOR="${2}"
         shift
         shift
       else
-        _exit_with_error "No selector provided after 'selector' argument"
+        echo "No selector provided after 'selector' argument. Aborting." >&2
+        exit 2
       fi
       ;;
 
-    ( 'domain' )
-      if [[ -n ${2+set} ]]
+    domain )
+      if [[ -n ${2+'set'} ]]
       then
         DOMAINS="${2}"
         shift
         shift
       else
-        _exit_with_error "No domain(s) provided after 'domain' argument"
+        echo "No domain(s) provided after 'domain' argument. Aborting." >&2
+        exit 2
       fi
       ;;
 
-    ( * )
+    * )
       __usage
-      _exit_with_error "Unknown options '${1}' ${2:+and \'${2}\'}"
+      echo -e "\nUnknown options ${1} ${2:-}. Aborting." >&2
+      exit 2
       ;;
 
   esac
@@ -126,7 +127,7 @@ then
     done < <(grep -v "^\s*$\|^\s*\#" /tmp/docker-mailserver/postfix-virtual.cf || true)
   fi
 else
-  tr ',' '\n' <<< "${DOMAINS}" >/tmp/vhost.dkim.tmp
+  tr ',' '\n' <<< "${DOMAINS}" > /tmp/vhost.dkim.tmp
 fi
 
 sort < /tmp/vhost.dkim.tmp | uniq >/tmp/vhost
@@ -134,7 +135,7 @@ rm /tmp/vhost.dkim.tmp
 
 if [[ ! -s /tmp/vhost ]]
 then
-  _log 'warn' 'No entries found, no keys to make'
+  echo "No entries found, no keys to make."
   exit 0
 fi
 
@@ -144,7 +145,7 @@ do
 
   if [[ ! -f "/tmp/docker-mailserver/opendkim/keys/${DKIM_DOMAIN}/${SELECTOR}.private" ]]
   then
-    _log 'info' "Creating DKIM private key '/tmp/docker-mailserver/opendkim/keys/${DKIM_DOMAIN}/${SELECTOR}.private'"
+    echo "Creating DKIM private key /tmp/docker-mailserver/opendkim/keys/${DKIM_DOMAIN}/${SELECTOR}.private"
 
     opendkim-genkey \
       --bits="${KEYSIZE}" \
@@ -158,7 +159,7 @@ do
   KEYTABLEENTRY="${SELECTOR}._domainkey.${DKIM_DOMAIN} ${DKIM_DOMAIN}:${SELECTOR}:/etc/opendkim/keys/${DKIM_DOMAIN}/${SELECTOR}.private"
   if [[ ! -f "/tmp/docker-mailserver/opendkim/KeyTable" ]]
   then
-    _log 'debug' 'Creating DKIM KeyTable'
+    echo "Creating DKIM KeyTable"
     echo "${KEYTABLEENTRY}" >/tmp/docker-mailserver/opendkim/KeyTable
   else
     if ! grep -q "${KEYTABLEENTRY}" "/tmp/docker-mailserver/opendkim/KeyTable"
@@ -171,7 +172,7 @@ do
   SIGNINGTABLEENTRY="*@${DKIM_DOMAIN} ${SELECTOR}._domainkey.${DKIM_DOMAIN}"
   if [[ ! -f /tmp/docker-mailserver/opendkim/SigningTable ]]
   then
-    _log 'debug' 'Creating DKIM SigningTable'
+    echo "Creating DKIM SigningTable"
     echo "*@${DKIM_DOMAIN} ${SELECTOR}._domainkey.${DKIM_DOMAIN}" >/tmp/docker-mailserver/opendkim/SigningTable
   else
     if ! grep -q "${SIGNINGTABLEENTRY}" /tmp/docker-mailserver/opendkim/SigningTable
@@ -184,7 +185,7 @@ done < <(grep -vE '^(\s*$|#)' /tmp/vhost)
 # create TrustedHosts if missing
 if [[ -d /tmp/docker-mailserver/opendkim ]] && [[ ! -f /tmp/docker-mailserver/opendkim/TrustedHosts ]]
 then
-  _log 'debug' 'Creating DKIM TrustedHosts'
+  echo "Creating DKIM TrustedHosts"
   echo "127.0.0.1" >/tmp/docker-mailserver/opendkim/TrustedHosts
   echo "localhost" >>/tmp/docker-mailserver/opendkim/TrustedHosts
 fi
diff --git a/target/bin/sedfile b/target/bin/sedfile
--- a/target/bin/sedfile
+++ b/target/bin/sedfile
@@ -9,33 +9,21 @@
 # Is a file change expected? --> use 'sedfile --strict -i'
 # Is a file change only on the first container run expected? --> use 'sedfile -i'
 
-if [[ -e /usr/local/bin/helpers/log.sh ]]
-then
-  # shellcheck source=../scripts/helpers/log.sh
-  source /usr/local/bin/helpers/log.sh
-else
-  # when running BATS (unit tests), this file is not located
-  # inside a container; as a consequence, we need to source
-  # from a different location
-  source target/scripts/helpers/log.sh
-fi
-
 set -ueo pipefail
 
-function __usage { echo "Usage: ${0} -i <replace/delete operation> <file>" ; }
-
-HASHTOOL='sha1sum'
+HASHTOOL="sha1sum"
 SKIP_ERROR=0
 
-if [[ ${#} -lt 3 ]]
+if [[ $# -lt 3 ]]
 then
-  _log 'error' 'At least three parameters must be given'
-  __usage
+  echo "Error:  At least, three parameters must be given."
+  echo "Syntax: sedfile -i <replace/delete operation> <file>"
+  echo
   exit 1
 fi >&2
 
-[[ -f /CONTAINER_START ]] && SKIP_ERROR=1 # hide error if container was restarted
-if [[ ${1} == '--strict' ]]               # show error every time
+[[ -f /CONTAINER_START ]] && SKIP_ERROR=1 # Hide error, if container was restarted.
+if [[ "${1}" == "--strict" ]]         # Show error every time.
 then
   SKIP_ERROR=0
   shift
@@ -45,14 +33,14 @@ fi
 FILE=${*: -1}
 
 OLD=$(${HASHTOOL} "${FILE}")
-sed "${@}"
+sed "$@"
 NEW=$(${HASHTOOL} "${FILE}")
 
 # fail if file was not modified
 if [[ ${OLD} == "${NEW}" ]] && [[ ${SKIP_ERROR} -eq 0 ]]
 then
-  _log 'error' "No difference after call to 'sed' in 'sedfile' (sed ${*})" >&2
+  echo "Error: sed $*"
   exit 1
-fi
+fi >&2
 
 exit 0
